-- ENIGMA OS V4.4 — SEGURANÇA, ACESSOS E AUDITORIA
-- Execute no Supabase SQL Editor.

create table if not exists public.enigma_usuarios (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique not null references auth.users(id) on delete cascade,
  nome text not null,
  email text,
  role text not null default 'vendedor' check (role in ('admin','gerente','vendedor','tecnico')),
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.enigma_auditoria (
  id bigint generated by default as identity primary key,
  auth_user_id uuid,
  usuario_nome text,
  usuario_role text,
  tabela text not null,
  operacao text not null,
  registro_id text,
  dados_anteriores jsonb,
  dados_novos jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.enigma_role()
returns text language sql stable security definer set search_path=public
as $$
  select role from public.enigma_usuarios
  where auth_user_id=auth.uid() and ativo=true limit 1
$$;

create or replace function public.enigma_tabela_permitida(p_tabela text, p_method text default null)
returns boolean language plpgsql stable security definer set search_path=public
as $$
declare r text := public.enigma_role();
declare m text := upper(coalesce(p_method,'GET'));
begin
  if r='admin' then return true; end if;
  if r is null then return false; end if;

  if p_tabela in ('financeiro_movimentacoes','financeiro_lancamentos','financeiro_categorias') then
    return r in ('gerente');
  end if;

  if p_tabela in ('avaliacoes_usados','seminovos') then
    return r in ('gerente','vendedor');
  end if;

  if p_tabela in ('caixa_sessoes','vendas','vendas_estornos') then
    return r in ('gerente','vendedor');
  end if;

  if p_tabela in ('ordens_servico','clientes') then
    return r in ('gerente','vendedor','tecnico');
  end if;

  if p_tabela in ('estoque','estoque_movimentacoes','estoque_historico','pelicula_grupos','pelicula_estoque_links','referencias_mercado') then
    return r in ('gerente','vendedor','tecnico');
  end if;

  return false;
end
$$;

alter table public.enigma_usuarios enable row level security;
alter table public.enigma_auditoria enable row level security;

drop policy if exists enigma_usuario_self on public.enigma_usuarios;
create policy enigma_usuario_self on public.enigma_usuarios
for select to authenticated
using (auth_user_id=auth.uid() or public.enigma_role()='admin');

drop policy if exists enigma_usuario_admin_write on public.enigma_usuarios;
create policy enigma_usuario_admin_write on public.enigma_usuarios
for all to authenticated
using (public.enigma_role()='admin')
with check (public.enigma_role()='admin');

drop policy if exists enigma_auditoria_read on public.enigma_auditoria;
create policy enigma_auditoria_read on public.enigma_auditoria
for select to authenticated
using (public.enigma_role() in ('admin','gerente'));



-- RLS somente em tabelas reais. Views são ignoradas automaticamente.
do $$
declare
  t text;
  kind "char";
  alvos text[] := ARRAY[
    'clientes','ordens_servico','estoque','estoque_movimentacoes','caixa_sessoes',
    'vendas','vendas_estornos','avaliacoes_usados','seminovos','pelicula_grupos',
    'pelicula_estoque_links','financeiro_movimentacoes','financeiro_lancamentos',
    'financeiro_categorias','referencias_mercado','estoque_historico'
  ];
begin
  foreach t in array alvos loop
    select c.relkind into kind
    from pg_class c join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='public' and c.relname=t;

    if kind in ('r','p') then
      execute format('alter table public.%I enable row level security',t);
      execute format('drop policy if exists enigma_authenticated_all on public.%I',t);
      execute format(
        'create policy enigma_authenticated_all on public.%I for all to authenticated using (public.enigma_tabela_permitida(%L, current_setting(''request.method'', true))) with check (public.enigma_tabela_permitida(%L, current_setting(''request.method'', true)))',
        t,t,t
      );
    end if;
  end loop;
end $$;

create or replace function public.enigma_auditar()
returns trigger language plpgsql security definer set search_path=public
as $$
declare p public.enigma_usuarios;
declare rid text;
begin
  select * into p from public.enigma_usuarios where auth_user_id=auth.uid() limit 1;
  rid := coalesce((to_jsonb(new)->>'id'),(to_jsonb(old)->>'id'));
  insert into public.enigma_auditoria(auth_user_id,usuario_nome,usuario_role,tabela,operacao,registro_id,dados_anteriores,dados_novos)
  values(auth.uid(),p.nome,p.role,TG_TABLE_NAME,TG_OP,rid,
    case when TG_OP in ('UPDATE','DELETE') then to_jsonb(old) else null end,
    case when TG_OP in ('INSERT','UPDATE') then to_jsonb(new) else null end);
  return coalesce(new,old);
end
$$;



-- Auditoria somente em tabelas reais; views são ignoradas.
do $$
declare
  t text;
  kind "char";
  alvos text[] := ARRAY[
    'clientes','ordens_servico','estoque','estoque_movimentacoes','caixa_sessoes',
    'vendas','avaliacoes_usados','seminovos','financeiro_movimentacoes','financeiro_lancamentos'
  ];
begin
  foreach t in array alvos loop
    select c.relkind into kind
    from pg_class c join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='public' and c.relname=t;

    if kind in ('r','p') then
      execute format('drop trigger if exists %I on public.%I','trg_audit_'||t,t);
      execute format(
        'create trigger %I after insert or update or delete on public.%I for each row execute function public.enigma_auditar()',
        'trg_audit_'||t,t
      );
    end if;
  end loop;
end $$;

-- PASSO 2: crie cada conta em Authentication > Users no painel do Supabase.
-- PASSO 3: depois rode UM INSERT por usuário, trocando e-mail/nome/função:
--
-- insert into public.enigma_usuarios(auth_user_id,nome,email,role)
-- select id,'SEU NOME',email,'admin' from auth.users where email='SEU_EMAIL';
--
-- Funções válidas: admin | gerente | vendedor | tecnico
--
-- IMPORTANTE: crie primeiro SUA conta como admin antes de testar o login.
